### ISSUE TITLE
Syntax error on any command line invocation

### ISSUE THREAD

**Issue by sethbro** [Angelmmiguel/svgi#11] opened 2017-06-07 20:14 UTC
I get this error when I try to use `svgi` in any way.

```
/Users/seth/.config/yarn/global/node_modules/svgi/index.js:36
          let svg = new SVG(filePath, result),
          ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

I am running node 4.8.3

**Comment by Angelmmiguel** [comment] 2017-06-07 22:10
Hello @sethbro,

The problem is related with the node version. I need to update the README to indicate that `svgi` works with node versions greater than 6.X.X. I don't expect to add support for older versions because it uses new ECMAScript syntax and features.

However, I know this is a problem and I want to propose a solution. Also, some users may want to use the tool but they don't have node installed. I'm working with [zeit/pkg](https://github.com/zeit/pkg) to provide an executable file with all the dependencies (#8). I would rather use node because the size of the files is big, but it's a good solution for this situations.

These files are not released yet. They worked on my machine, but please, feel free to test them and provide your feedback. Thanks :)

[svgi-linux-x64-1.0.0.tar.gz](https://github.com/Angelmmiguel/svgi/files/1059460/svgi-linux-x64-1.0.0.tar.gz)
[svgi-macos-x64-1.0.0.tar.gz](https://github.com/Angelmmiguel/svgi/files/1059458/svgi-macos-x64-1.0.0.tar.gz)
[svgi-win-x64-1.0.0.tar.gz](https://github.com/Angelmmiguel/svgi/files/1059459/svgi-win-x64-1.0.0.tar.gz)

**Comment by sethbro** [comment] 2017-06-07 22:26
@Angelmmiguel Thanks for the quick response. I assumed the issue was with my node version (though I didn't realize node 6 had built-in ES6 support—that's pretty cool).

I can probably upgrade to node 6, but if not I'll give those executables a try. Thanks again.

**Comment by Angelmmiguel** [comment] 2017-06-07 22:38
@sethbro yes, the node team is adding the new ECMAScript features progressively. You can check the current progress in [node.green](http://node.green).

> I can probably upgrade to node 6, but if not I'll give those executables a try. Thanks again.

That's good! I'm using the current LTS version of [node](https://nodejs.org/en/) (6.11.0).

I'm gonna close this task. Please, feel free to provide your feedback about the executable files (if you try them) in #8 or open a new issue if you have any other question.

Thanks!

**Closed by Angelmmiguel** 2017-06-07 22:38 UTC
